#!/usr/bin/ruby
load "lib/video.rb"
load "lib/music.rb"

# check-media <type> <path>

def usage()
    puts "Usage:"
    exit
end

conf = Hash.new

if (ARGV.count != 2)
    usage()
end

verbose = 0
if (ARGV[0] and ARGV[0] == "video")
    movie = ListMovie.new(ARGV[1])
    movie.list
    movie.check
    # movie.Result
end

if (ARGV[0] and ARGV[0] == "musique")
	verbose = 1
    music = ListMusic.new(ARGV[1])
    music.list
    music.check
    # music.Result
end
